import { Injectable } from "@nestjs/common";
import { Request } from "express";
import { CurrencyInfo } from "src/constants";

@Injectable()
export class BattleserverEnterService {
    private readonly battleserverEnter = {
        ErrorCode: 0,
        MonsterList: [
            // {
            //     Aid: 1,
            //     Index: "MOB_MP_Hirume_N",
            //     Grade: 5,
            //     Level: 1,
            //     MaxHP: 32000,
            //     MaxAP: 0,
            //     HP: 32000,
            //     AP: 0,
            //     GridPosIndex: 0,
            //     TeamId: 1,
            //     WaveStep: 0,
            // },
            // {
            //     Aid: 2,
            //     Index: "MOB_MP_Hirume_N",
            //     Grade: 5,
            //     Level: 1,
            //     MaxHP: 32000,
            //     MaxAP: 0,
            //     HP: 32000,
            //     AP: 0,
            //     GridPosIndex: 1,
            //     TeamId: 1,
            //     WaveStep: 0,
            // },
            // {
            //     Aid: 3,
            //     Index: "MOB_MP_Hirume_N",
            //     Grade: 5,
            //     Level: 1,
            //     MaxHP: 32000,
            //     MaxAP: 0,
            //     HP: 32000,
            //     AP: 0,
            //     GridPosIndex: 2,
            //     TeamId: 1,
            //     WaveStep: 0,
            // },
            // {
            //     Aid: 4,
            //     Index: "MOB_MP_Hirume_N",
            //     Grade: 5,
            //     Level: 1,
            //     MaxHP: 32000,
            //     MaxAP: 0,
            //     HP: 32000,
            //     AP: 0,
            //     GridPosIndex: 3,
            //     TeamId: 1,
            //     WaveStep: 0,
            // },
            // {
            //     Aid: 5,
            //     Index: "MOB_MP_Hirume_N",
            //     Grade: 5,
            //     Level: 1,
            //     MaxHP: 32000,
            //     MaxAP: 0,
            //     HP: 32000,
            //     AP: 0,
            //     GridPosIndex: 4,
            //     TeamId: 1,
            //     WaveStep: 0,
            // },
            // {
            //     Aid: 6,
            //     Index: "MOB_MP_Hirume_N",
            //     Grade: 5,
            //     Level: 1,
            //     MaxHP: 32000,
            //     MaxAP: 0,
            //     HP: 32000,
            //     AP: 0,
            //     GridPosIndex: 5,
            //     TeamId: 1,
            //     WaveStep: 0,
            // },
            // {
            //     Aid: 7,
            //     Index: "MOB_MP_Hirume_N",
            //     Grade: 5,
            //     Level: 1,
            //     MaxHP: 32000,
            //     MaxAP: 0,
            //     HP: 32000,
            //     AP: 0,
            //     GridPosIndex: 6,
            //     TeamId: 1,
            //     WaveStep: 0,
            // },
            // {
            //     Aid: 8,
            //     Index: "MOB_MP_Hirume_N",
            //     Grade: 5,
            //     Level: 1,
            //     MaxHP: 32000,
            //     MaxAP: 0,
            //     HP: 32000,
            //     AP: 0,
            //     GridPosIndex: 7,
            //     TeamId: 1,
            //     WaveStep: 0,
            // },
            {
                Aid: 9,
                Index: "MOB_MP_Hirume_N",
                Grade: 5,
                Level: 1,
                MaxHP: 32000,
                MaxAP: 0,
                HP: 32000,
                AP: 0,
                GridPosIndex: 8,
                TeamId: 1,
                WaveStep: 0,
            },
        ],
        PCList: [
            {
                Aid: 100000010,
                PCID: 100000010,
                Index: "Char_PECS_Azaz_N",
                Grade: 5,
                Level: 100,
                MaxHP: 9999,
                MaxAP: 0,
                HP: 9999,
                GridPosIndex: 3,
                TeamId: 0,
                IsFriend: 0,
            },
        ],
        CurrencyInfo: CurrencyInfo,
    };
    getBattleserverEnter(req: Request) {
        return {
            ...this.battleserverEnter,
            Sequence: req.body.Sequence + 2,
        };
    }
}
